# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prevencion',
        ),
    ]
