# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0003_prevencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevencion',
            name='descripcion',
            field=models.TextField(max_length=600),
        ),
    ]
