# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0004_auto_20171025_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prevencion',
        ),
    ]
