# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0007_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
