# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0009_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.RemoveField(
            model_name='prevencion',
            name='medidas',
        ),
        migrations.AddField(
            model_name='medida',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hogar.Prevencion'),
        ),
    ]
