# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0011_norma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Norma',
        ),
    ]
