# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hogar', '0013_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hogar.Prevencion'),
        ),
    ]
